# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "d:/Trabajos_UC/9 noveno semestre/SEP/Ayudantia 5/Arcchivos nuevos/AYUD_05/AYUD_05.runs/impl_1/.Xil/Vivado-46276-DESKTOP-A0CU7UE/dc_drv.0/dc/prj_ip.runs/dbg_hub_synth_1/dbg_hub.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "dbg_hub_synth_1" START { ROLLUP_AUTO }
set_param project.singleFileAddWarning.threshold 0
set_param chipscope.maxJobs 3
set_param chipscope.flow 0
set_param synth.enableIncremental 0
set_param project.vivado.isBlockSynthRun true
set_msg_config -msgmgr_mode ooc_run
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir {d:/Trabajos_UC/9 noveno semestre/SEP/Ayudantia 5/Arcchivos nuevos/AYUD_05/AYUD_05.runs/impl_1/.Xil/Vivado-46276-DESKTOP-A0CU7UE/dc_drv.0/dc/prj_ip.cache/wt} [current_project]
set_property parent.project_path {d:/Trabajos_UC/9 noveno semestre/SEP/Ayudantia 5/Arcchivos nuevos/AYUD_05/AYUD_05.runs/impl_1/.Xil/Vivado-46276-DESKTOP-A0CU7UE/dc_drv.0/dc/prj_ip.xpr} [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:zybo-z7-10:part0:1.2 [current_project]
set_property ip_repo_paths {
  {d:/Trabajos_UC/9 noveno semestre/SEP/Ayudantia 5/Arcchivos nuevos/AYUD_05/RGB_FULL_1.0}
  {d:/Trabajos_UC/9 noveno semestre/SEP/Ayudantia 5/Arcchivos nuevos/AYUD_05/RGB_DRIVER_1.0}
  {d:/Trabajos_UC/9 noveno semestre/SEP/Ayudantia 5/Arcchivos nuevos/AYUD_05/RGB_driver_1.0}
  {d:/Trabajos_UC/9 noveno semestre/SEP/Ayudantia 5/Arcchivos nuevos/AYUD_05/RGB_driver_1.0}
} [current_project]
update_ip_catalog
set_property ip_output_repo {d:/Trabajos_UC/9 noveno semestre/SEP/Ayudantia 5/Arcchivos nuevos/AYUD_05/AYUD_05.runs/impl_1/{D:/Trabajos_UC/9 noveno semestre/SEP/Ayudantia 5/Arcchivos nuevos/AYUD_05/AYUD_05.cache/ip}} [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_ip -quiet {{d:/Trabajos_UC/9 noveno semestre/SEP/Ayudantia 5/Arcchivos nuevos/AYUD_05/AYUD_05.runs/impl_1/.Xil/Vivado-46276-DESKTOP-A0CU7UE/dc_drv.0/dc/prj_ip.srcs/sources_1/ip/dbg_hub/dbg_hub.xci}}
set_property used_in_implementation false [get_files -all {{d:/Trabajos_UC/9 noveno semestre/SEP/Ayudantia 5/Arcchivos nuevos/AYUD_05/AYUD_05.runs/impl_1/.Xil/Vivado-46276-DESKTOP-A0CU7UE/dc_drv.0/dc/prj_ip.srcs/sources_1/ip/dbg_hub/constraints/xsdbm_cc_early.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/Trabajos_UC/9 noveno semestre/SEP/Ayudantia 5/Arcchivos nuevos/AYUD_05/AYUD_05.runs/impl_1/.Xil/Vivado-46276-DESKTOP-A0CU7UE/dc_drv.0/dc/prj_ip.srcs/sources_1/ip/dbg_hub/constraints/xsdbm_cc_late.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/Trabajos_UC/9 noveno semestre/SEP/Ayudantia 5/Arcchivos nuevos/AYUD_05/AYUD_05.runs/impl_1/.Xil/Vivado-46276-DESKTOP-A0CU7UE/dc_drv.0/dc/prj_ip.srcs/sources_1/ip/dbg_hub/constraints/xsdbm_gc_late.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/Trabajos_UC/9 noveno semestre/SEP/Ayudantia 5/Arcchivos nuevos/AYUD_05/AYUD_05.runs/impl_1/.Xil/Vivado-46276-DESKTOP-A0CU7UE/dc_drv.0/dc/prj_ip.srcs/sources_1/ip/dbg_hub/dbg_hub_ooc.xdc}}]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top dbg_hub -part xc7z010clg400-1 -mode out_of_context
OPTRACE "synth_design" END { }

rename_ref -prefix_all dbg_hub_

OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef dbg_hub.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
OPTRACE "synth reports" END { }

if { [catch {
  file copy -force {d:/Trabajos_UC/9 noveno semestre/SEP/Ayudantia 5/Arcchivos nuevos/AYUD_05/AYUD_05.runs/impl_1/.Xil/Vivado-46276-DESKTOP-A0CU7UE/dc_drv.0/dc/prj_ip.runs/dbg_hub_synth_1/dbg_hub.dcp} {d:/Trabajos_UC/9 noveno semestre/SEP/Ayudantia 5/Arcchivos nuevos/AYUD_05/AYUD_05.runs/impl_1/.Xil/Vivado-46276-DESKTOP-A0CU7UE/dc_drv.0/dc/prj_ip.srcs/sources_1/ip/dbg_hub/dbg_hub.dcp}
} _RESULT ] } { 
  send_msg_id runtcl-3 error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}

if { [catch {
  write_verilog -force -mode synth_stub {d:/Trabajos_UC/9 noveno semestre/SEP/Ayudantia 5/Arcchivos nuevos/AYUD_05/AYUD_05.runs/impl_1/.Xil/Vivado-46276-DESKTOP-A0CU7UE/dc_drv.0/dc/prj_ip.srcs/sources_1/ip/dbg_hub/dbg_hub_stub.v}
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode synth_stub {d:/Trabajos_UC/9 noveno semestre/SEP/Ayudantia 5/Arcchivos nuevos/AYUD_05/AYUD_05.runs/impl_1/.Xil/Vivado-46276-DESKTOP-A0CU7UE/dc_drv.0/dc/prj_ip.srcs/sources_1/ip/dbg_hub/dbg_hub_stub.vhdl}
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_verilog -force -mode funcsim {d:/Trabajos_UC/9 noveno semestre/SEP/Ayudantia 5/Arcchivos nuevos/AYUD_05/AYUD_05.runs/impl_1/.Xil/Vivado-46276-DESKTOP-A0CU7UE/dc_drv.0/dc/prj_ip.srcs/sources_1/ip/dbg_hub/dbg_hub_sim_netlist.v}
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode funcsim {d:/Trabajos_UC/9 noveno semestre/SEP/Ayudantia 5/Arcchivos nuevos/AYUD_05/AYUD_05.runs/impl_1/.Xil/Vivado-46276-DESKTOP-A0CU7UE/dc_drv.0/dc/prj_ip.srcs/sources_1/ip/dbg_hub/dbg_hub_sim_netlist.vhdl}
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if {[file isdir {d:/Trabajos_UC/9 noveno semestre/SEP/Ayudantia 5/Arcchivos nuevos/AYUD_05/AYUD_05.runs/impl_1/.Xil/Vivado-46276-DESKTOP-A0CU7UE/dc_drv.0/dc/prj_ip.ip_user_files/ip/dbg_hub}]} {
  catch { 
    file copy -force {{d:/Trabajos_UC/9 noveno semestre/SEP/Ayudantia 5/Arcchivos nuevos/AYUD_05/AYUD_05.runs/impl_1/.Xil/Vivado-46276-DESKTOP-A0CU7UE/dc_drv.0/dc/prj_ip.srcs/sources_1/ip/dbg_hub/dbg_hub_stub.v}} {d:/Trabajos_UC/9 noveno semestre/SEP/Ayudantia 5/Arcchivos nuevos/AYUD_05/AYUD_05.runs/impl_1/.Xil/Vivado-46276-DESKTOP-A0CU7UE/dc_drv.0/dc/prj_ip.ip_user_files/ip/dbg_hub}
  }
}

if {[file isdir {d:/Trabajos_UC/9 noveno semestre/SEP/Ayudantia 5/Arcchivos nuevos/AYUD_05/AYUD_05.runs/impl_1/.Xil/Vivado-46276-DESKTOP-A0CU7UE/dc_drv.0/dc/prj_ip.ip_user_files/ip/dbg_hub}]} {
  catch { 
    file copy -force {{d:/Trabajos_UC/9 noveno semestre/SEP/Ayudantia 5/Arcchivos nuevos/AYUD_05/AYUD_05.runs/impl_1/.Xil/Vivado-46276-DESKTOP-A0CU7UE/dc_drv.0/dc/prj_ip.srcs/sources_1/ip/dbg_hub/dbg_hub_stub.vhdl}} {d:/Trabajos_UC/9 noveno semestre/SEP/Ayudantia 5/Arcchivos nuevos/AYUD_05/AYUD_05.runs/impl_1/.Xil/Vivado-46276-DESKTOP-A0CU7UE/dc_drv.0/dc/prj_ip.ip_user_files/ip/dbg_hub}
  }
}
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "dbg_hub_synth_1" END { }
